# Generated by Django 5.2.17 on 2026-09-26 00:32

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audit_uuid', models.UUIDField(editable=False, unique=True)),
                ('at_ts', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('actor_kind', models.CharField(choices=[('IDENTITY', 'Identity'), ('SERVICE', 'Service'), ('SYSTEM_JOB', 'System Job'), ('ANONYMOUS', 'Anonymous')], max_length=10)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('subject_kind', models.CharField(max_length=32)),
                ('subject_id', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied')], max_length=7)),
                ('before_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('after_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('payload_ref', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('application_id', models.CharField(blank=True, max_length=64, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('session_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=64, null=True)),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('stream', models.CharField(max_length=3)),
                ('seq_in_stream', models.BigIntegerField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('row_hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'uiap_audit"."audit_events',
                'indexes': [models.Index(fields=['stream', 'seq_in_stream'], name='audit_stream_seq_idx'), models.Index(fields=['subject_kind', 'subject_id'], name='audit_subject_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['credential.added', 'credential.revoked', 'credential.verified', 'identity.activated', 'identity.created', 'identity.deleted', 'identity.deletion_requested', 'identity.locked', 'identity.reinstated', 'identity.suspended', 'identity.unlocked', 'password.changed'])), name='audit_events_action_taxonomy_check'), models.CheckConstraint(condition=models.Q(('stream__in', ['SEC', 'IDN', 'APP', 'ADM', 'POL'])), name='audit_events_stream_check'), models.CheckConstraint(condition=models.Q(('outcome__in', ['SUCCESS', 'DENIED'])), name='audit_events_outcome_check'), models.CheckConstraint(condition=models.Q(models.Q(('context__isnull', False), _negated=True), models.Q(models.Q(('context__has_key', 'phc'), _negated=True), models.Q(('context__has_key', 'password'), _negated=True)), _connector='OR'), name='audit_events_no_secret_keys_check')],
            },
        ),
        migrations.CreateModel(
            name='AuditRoot',
            fields=[
                ('root_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream', models.CharField(max_length=3)),
                ('partition', models.CharField(max_length=7)),
                ('seq_from', models.BigIntegerField()),
                ('seq_to', models.BigIntegerField()),
                ('root_hash', models.CharField(max_length=64)),
                ('prev_root_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'uiap_audit"."audit_roots',
                'indexes': [models.Index(fields=['stream', 'partition'], name='audit_roots_stream_idx')],
                'constraints': [models.UniqueConstraint(fields=('stream', 'partition', 'seq_to'), name='audit_roots_stream_partition_seq_to_uc')],
            },
        ),
    ]
