# Generated by Django 5.2.17 on 2026-09-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.UniqueConstraint(fields=('stream', 'seq_in_stream'), name='audit_events_stream_seq_uc'),
        ),
    ]
