# Generated by Django 5.2.17 on 2026-09-16 04:26
#
# P0.4 audit notes (ADR 0001):
#   - Deliberately NO dependency on auth/contenttypes/admin (RULE 8/12):
#     `migrate outbox` touches only uiap_access.outbox_events.
#   - db_table is fully schema-qualified ('uiap_access"."outbox_events') so
#     the table can only exist inside uiap_access (A-3); django_migrations
#     bookkeeping lands in uiap_migration via the connection search_path.
#   - Reversible: reverse() drops the table and restores pre-migration state
#     (single CreateModel op; verified by tests/integration/database).
#   - Only non-unique index is the PENDING partial claim index (§34.4);
#     event_id uniqueness comes from the field-level UNIQUE and the
#     (subject, seq) uniqueness from the UniqueConstraint below.

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(db_collation='C', max_length=255)),
                ('seq', models.BigIntegerField()),
                ('event_id', models.UUIDField(editable=False, unique=True)),
                ('event_type', models.CharField(db_collation='C', max_length=255)),
                ('dataversion', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_collation='C', max_length=64)),
                ('payload_ref', models.TextField(blank=True, null=True)),
                ('partition_key', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_state', models.CharField(choices=[('PENDING', 'Pending publish'), ('PUBLISHED', 'Published to the stream'), ('ACKED', 'Acknowledged by all consumer groups'), ('FAILED', 'Parked in DLQ after retry budget')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_collation='C', max_length=64, null=True)),
                ('request_id', models.CharField(blank=True, db_collation='C', max_length=64, null=True)),
                ('correlation_id', models.CharField(blank=True, db_collation='C', max_length=64, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'uiap_access"."outbox_events',
                'indexes': [models.Index(condition=models.Q(('publish_state', 'PENDING')), fields=['available_at'], name='outbox_pending_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'seq'), name='outbox_subject_seq_key'), models.CheckConstraint(condition=models.Q(('publish_state__in', ['PENDING', 'PUBLISHED', 'ACKED', 'FAILED'])), name='outbox_publish_state_check'), models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='outbox_attempts_nonnegative_check')],
            },
        ),
    ]
