# Generated by Django 5.2.17 on 2026-09-20 12:22
#
# P0.6.1 audit notes (ADR 0002):
#   - Deliberately NO dependency on auth/contenttypes/admin (P0.4 RULE 8/12
#     discipline continues): `migrate identity` touches only uiap_identity.
#   - db_table is fully schema-qualified ('uiap_identity"."<table>') so the
#     tables can only exist inside uiap_identity (A-3 pattern); django_
#     migrations bookkeeping lands in uiap_migration via the search_path.
#   - Status CHECK includes ABANDONED per the §11.4 state machine (D-1:
#     §11.2's enumeration omits it — discrepancy documented, doc untouched).
#   - "status partial (ops scans)" (§34.4) = live (non-terminal) rows only;
#     "kind partial" = live credentials (PENDING/ACTIVE).  Inferences
#     recorded in ADR 0002.
#   - Reversible: three CreateModel ops; reverse() drops exactly these tables.

import contexts.identity.ids
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=contexts.identity.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HUMAN', 'Human'), ('ORGANIZATION', 'Organization'), ('SERVICE', 'Service')], max_length=12)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('PENDING_DELETION', 'Pending Deletion'), ('DELETED', 'Deleted'), ('ABANDONED', 'Abandoned'), ('MERGED', 'Merged')], max_length=16)),
                ('verification_level', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('IAL1', 'Ial1'), ('IAL2', 'Ial2')], max_length=10)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('region_tag', models.CharField(max_length=64)),
                ('row_version', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'uiap_identity"."identities',
                'indexes': [django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='identities_created_at_brin'), models.Index(condition=models.Q(('status__in', ['ACTIVE', 'LOCKED', 'PENDING_DELETION', 'PROVISIONAL', 'SUSPENDED']), _negated=True), fields=['status'], name='identities_status_live_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['HUMAN', 'ORGANIZATION', 'SERVICE'])), name='identities_type_check'), models.CheckConstraint(condition=models.Q(('status__in', ['ABANDONED', 'ACTIVE', 'DELETED', 'LOCKED', 'MERGED', 'PENDING_DELETION', 'PROVISIONAL', 'SUSPENDED'])), name='identities_status_check'), models.CheckConstraint(condition=models.Q(('verification_level__in', ['IAL1', 'IAL2', 'UNVERIFIED'])), name='identities_verification_level_check')],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=contexts.identity.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=14)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('STALE', 'Stale'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], max_length=7)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('risk_flags', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True)),
                ('mfa_strength_rank', models.IntegerField(blank=True, null=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='identity.identity')),
            ],
            options={
                'db_table': 'uiap_identity"."credentials',
                'indexes': [models.Index(fields=['identity', 'status'], name='cred_identity_status_idx'), models.Index(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=['kind'], name='credentials_kind_live_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__in', ['EMAIL', 'PASSKEY', 'PASSWORD', 'PHONE', 'RECOVERY_CODES', 'TOTP'])), name='credentials_kind_check'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'EXPIRED', 'PENDING', 'REVOKED', 'STALE'])), name='credentials_status_check')],
            },
        ),
        migrations.CreateModel(
            name='IdentityStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('PENDING_DELETION', 'Pending Deletion'), ('DELETED', 'Deleted'), ('ABANDONED', 'Abandoned'), ('MERGED', 'Merged')], max_length=16)),
                ('valid_from', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='identity.identity')),
            ],
            options={
                'db_table': 'uiap_identity"."identity_status_history',
                'constraints': [models.UniqueConstraint(fields=('id', 'valid_from'), name='identity_status_history_id_valid_from_uc')],
            },
        ),
    ]
