# P0.6.2-A (ADR-0003): uiap_identity.password_secrets — §34.4 typed secret
# table for PASSWORD credentials.  Hash-only (PHC), no hot index, params
# NOT NULL.  Generated by Django 5.2.17; audited by hand against the
# architecture before commit.

import contexts.identity.ids
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSecret',
            fields=[
                ('id', models.UUIDField(default=contexts.identity.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('phc', models.CharField(max_length=256)),
                ('argon_memory_kib', models.PositiveIntegerField()),
                ('argon_time_cost', models.PositiveSmallIntegerField()),
                ('argon_parallelism', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('DISABLED', 'Disabled')], max_length=10)),
                ('breach_checked_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('row_version', models.BigIntegerField(default=1)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_secrets', to='identity.credential')),
            ],
            options={
                'db_table': 'uiap_identity"."password_secrets',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'SUPERSEDED', 'DISABLED'])), name='password_secrets_status_check'), models.CheckConstraint(condition=models.Q(('phc__startswith', '$argon2id$')), name='password_secrets_phc_argon2id_check'), models.CheckConstraint(condition=models.Q(('argon_memory_kib__gte', 8192), ('argon_memory_kib__lte', 1048576)), name='password_secrets_memory_bounds_check'), models.CheckConstraint(condition=models.Q(('argon_time_cost__gte', 1), ('argon_time_cost__lte', 10)), name='password_secrets_time_bounds_check'), models.CheckConstraint(condition=models.Q(('argon_parallelism__gte', 1), ('argon_parallelism__lte', 8)), name='password_secrets_parallelism_bounds_check')],
            },
        ),
    ]
